'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import toast from 'react-hot-toast';
import { blogApi, Blog, CreateBlogData, UpdateBlogData } from '@/lib/blog-api';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { getErrorMessage } from '@/lib/error-message';

interface BlogEditorProps {
  initialData?: Blog;
  mode: 'create' | 'edit';
}

export function BlogEditor({ initialData, mode }: BlogEditorProps) {
  const [title, setTitle] = useState(initialData?.title || '');
  const [content, setContent] = useState(initialData?.content || '');
  const [summary, setSummary] = useState(initialData?.summary || '');
  const [isPublished, setIsPublished] = useState(initialData?.isPublished || false);
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();

  const wordCount = content.split(/\s+/).filter(Boolean).length;
  const readTime = Math.max(1, Math.round(wordCount / 200));

  const handleSubmit = async (publishState: boolean) => {
    if (!title.trim()) {
      toast.error('Title is required');
      return;
    }
    if (content.trim().length < 10) {
      toast.error('Content must be at least 10 characters');
      return;
    }

    setIsLoading(true);
    try {
      if (mode === 'create') {
        const data: CreateBlogData = {
          title: title.trim(),
          content: content.trim(),
          isPublished: publishState,
          summary: summary.trim() || undefined,
        };
        await blogApi.create(data);
        toast.success(publishState ? 'Story published! 🎉' : 'Draft saved');
      } else {
        const data: UpdateBlogData = {
          title: title.trim(),
          content: content.trim(),
          isPublished: publishState,
          summary: summary.trim() || undefined,
        };
        await blogApi.update(initialData!.id, data);
        toast.success(publishState ? 'Story published! 🎉' : 'Changes saved');
      }
      router.push('/dashboard');
    } catch (error: unknown) {
      toast.error(getErrorMessage(error, `Failed to ${mode === 'create' ? 'create' : 'update'} story`));
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="relative">
        <input
          type="text"
          required
          maxLength={200}
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className="input-title w-full"
          placeholder="Your story title…"
        />
        <div className="flex justify-between mt-2">
          <p className="text-xs text-ink-muted">
            {title.length > 0 && (
              <span>
                Slug: <span className="font-mono">{title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}</span>
              </span>
            )}
          </p>
          <p className="text-xs text-ink-muted">{title.length}/200</p>
        </div>
      </div>

      {/* Summary */}
      <div>
        <label className="block text-sm font-medium text-ink mb-2">
          Summary
          <span className="ml-1.5 text-xs font-normal text-ink-muted">(optional — auto-generated by AI if blank)</span>
        </label>
        <textarea
          maxLength={500}
          rows={2}
          value={summary}
          onChange={(e) => setSummary(e.target.value)}
          className="input-field resize-none"
          placeholder="A short hook to draw readers in…"
        />
        <p className="mt-1.5 text-xs text-ink-muted text-right">{summary.length}/500</p>
      </div>

      {/* Content */}
      <div>
        <label className="block text-sm font-medium text-ink mb-2">
          Content <span className="text-red-500">*</span>
        </label>
        <textarea
          required
          rows={22}
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="input-field resize-y leading-relaxed"
          placeholder="Tell your story here…&#10;&#10;Use blank lines to separate paragraphs."
          style={{ fontFamily: 'Merriweather, Georgia, serif', fontSize: '1.0625rem', lineHeight: '1.85' }}
        />
        <div className="flex items-center justify-between mt-2">
          <p className="text-xs text-ink-muted">
            {wordCount} {wordCount === 1 ? 'word' : 'words'}
            {wordCount > 0 && <> · ~{readTime} min read</>}
          </p>
          <p className="text-xs text-ink-muted">
            Plain text · paragraphs separated by blank lines
          </p>
        </div>
      </div>

      {/* Publish toggle */}
      <div className="bg-surface rounded-xl border border-border p-4 flex items-center justify-between gap-4">
        <div>
          <p className="text-sm font-medium text-ink">
            {isPublished ? 'Publish immediately' : 'Save as draft'}
          </p>
          <p className="text-xs text-ink-muted mt-0.5">
            {isPublished
              ? 'This story will be visible on the public feed.'
              : 'Only you can see drafts. You can publish later.'}
          </p>
        </div>
        <button
          type="button"
          role="switch"
          aria-checked={isPublished}
          onClick={() => setIsPublished(!isPublished)}
          className={`toggle-track w-11 h-6 flex-shrink-0 ${isPublished ? 'bg-emerald-500' : 'bg-neutral-200'}`}
        >
          <div className={`toggle-thumb ${isPublished ? 'translate-x-5' : 'translate-x-0.5'}`} />
        </button>
      </div>

      {/* Action bar */}
      <div className="flex items-center gap-3 pt-2 border-t border-border">
        <button
          type="button"
          disabled={isLoading}
          onClick={() => handleSubmit(isPublished)}
          className="btn-primary flex items-center gap-2 px-6"
        >
          {isLoading ? (
            <><LoadingSpinner size="sm" />{mode === 'create' ? 'Creating…' : 'Saving…'}</>
          ) : isPublished ? (
            <>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              {mode === 'create' ? 'Publish Story' : 'Save & Publish'}
            </>
          ) : (
            mode === 'create' ? 'Save Draft' : 'Save Changes'
          )}
        </button>

        {!isPublished && mode === 'create' && (
          <button
            type="button"
            disabled={isLoading}
            onClick={() => { setIsPublished(true); handleSubmit(true); }}
            className="btn-accent flex items-center gap-2"
          >
            Publish now
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </button>
        )}

        <button
          type="button"
          onClick={() => router.push('/dashboard')}
          className="btn-ghost ml-auto"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}

interface BlogEditorProps {
  initialData?: Blog;
  mode: 'create' | 'edit';
}

